### ISSUE TITLE
avoid to add duplicate fragments in stack

### ISSUE THREAD

**Issue by pishguy** [amorenew/FlutterBlocFragment#3]
in current implementation there is another issue as, when multiple click on for example `fragment_1`, there is in stack and after click i have duplicate fragment in stack as same

**Comment by amorenew** [comment]
@MahdiPishguy 
I published a new release with a fix to this issue
I will ask bloc developer for the wrong state  `BlocProvider.of() called with a context that does not contain a Bloc of type Bloc<dynamic, dynamic>`.

**Comment by pishguy** [comment]
@amorenew it seems this problem solved

**Comment by amorenew** [comment]
@MahdiPishguy No, I just forgot to of<BlocName>() in the drawer .. a new issue

**Comment by amorenew** [comment]
@MahdiPishguy if new code solves your issue then close this issue.
