### ISSUE TITLE
Invalid value: Not in range 0..1, inclusive: -1

### ISSUE THREAD

**Issue by pishguy** [amorenew/FlutterBlocFragment#4]
I get this error when i click on buttons to replace fragment

> RangeError (index): Invalid value: Not in range 0..1, inclusive: -1
> When the exception was thrown, this was the stack:
> #0      List.[] (dart:core-patch/growable_array.dart:145:60)
> #1      FragmentManager.getCurrentFragment (../fragment_bloc/fragment_manager.dart:97:22)

```
  Widget getCurrentFragment(int index) {
    if (_fragments.isEmpty) addFragment(getRoutes().entries.first.key);
    return _fragments[index];  //<-------------------
  }
```

**Comment by pishguy** [comment]
https://github.com/MahdiPishguy/fragment-sample

**Comment by amorenew** [comment]
@MahdiPishguy I just renamed get name to get route name

  @override
  String getName() {
    return PageScreenSections;
  }

  @override
  String getRouteName() {
    return null;
  }

**Comment by pishguy** [comment]
@amorenew yeah i'm so sorry, i fixed

**Comment by amorenew** [comment]
@MahdiPishguy No problem I should add a guideline but I don't know how could I publish a pure dart library
Tutorials are about flutter plugin

**Comment by pishguy** [comment]
@amorenew i don't have any information about that
