### ISSUE TITLE
passing parameteres for fragments

### ISSUE THREAD

**Issue by pishguy** [amorenew/FlutterBlocFragment#5]
i want to pass some parameters for fragments. with this implementation we can't and i want to know whats best solution about this issue

**Comment by amreniouinnovent** [comment]
@MahdiPishguy check how I pass the title and make instead of String a Map<String, dynamic>

**Comment by pishguy** [comment]
@amreniouinnovent my mean is passing parameter between fragments

**Comment by amreniouinnovent** [comment]
@MahdiPishguy same like the title it could be added to the event
in   FragmentManager().addFragment(event.routeName);  could update data too

```
    if (event is FragmentNavigateEvent) {
      if (!FragmentManager().isExist(event.routeName)) {
        FragmentManager().addFragment(event.routeName);
      }
      final int currentIndex =
          FragmentManager().navigateToName(event.routeName);
      print('bloc currentIndex:$currentIndex');
      yield FragmentCurrentState(currentIndex);

```

**Comment by pishguy** [comment]
@amreniouinnovent i'm not sure for this implementation, because i have more parameter, not only single parameter, whats your idea?

**Comment by amreniouinnovent** [comment]
@MahdiPishguy here you will add a parameter like a title in the fragment interface and fragment 1
https://github.com/amorenew/FlutterBlocFragment/blob/master/lib/fragments/fragment1.dart
and same like   int navigateToName(String fragmentName) {
  }
you can make updateData(String fragmentName,dynamic data)

**Comment by amreniouinnovent** [comment]
more than value could be Map<String,dynamic>

**Comment by pishguy** [comment]
@amreniouinnovent thanks, i check that

**Comment by pishguy** [comment]
> 
> 
> @MahdiPishguy same like the title it could be added to the event
> in FragmentManager().addFragment(event.routeName); could update data too
> 
> ```
>     if (event is FragmentNavigateEvent) {
>       if (!FragmentManager().isExist(event.routeName)) {
>         FragmentManager().addFragment(event.routeName);
>       }
>       final int currentIndex =
>           FragmentManager().navigateToName(event.routeName);
>       print('bloc currentIndex:$currentIndex');
>       yield FragmentCurrentState(currentIndex);
> ```

i don't understood how can i pass value

**Comment by amreniouinnovent** [comment]
@MahdiPishguy in navigateToName there is a for loop
once you catch the matched fragment pass the value to it

 (value.child as Fragment).setData(value );

```
 _fragments.asMap().forEach((int index, Widget value) {
      if (value is Fragment && value.getRouteName() == fragmentName) {
        fragmentIndex = index;
      } else if (value is BlocProvider &&
          value.child is Fragment &&
          (value.child as Fragment).getRouteName() == fragmentName) {
        fragmentIndex = index;
      } else if (value is MultiBlocProvider &&
          value.child is Fragment &&
          (value.child as Fragment).getRouteName() == fragmentName) {
        fragmentIndex = index;
      }
    });
```

**Comment by pishguy** [comment]
@amreniouinnovent your mean is i should use `switch()` statement?

**Comment by amreniouinnovent** [comment]
@MahdiPishguy  No. just in navigateToName pass your data as a new parameter then inside the existing for loop use (value.child as Fragment).setData(value );

**Comment by amreniouinnovent** [comment]
so Navigation Event have new data parameter then navigateToName passing the data to the Fragment

don't forget to add a data field to Fragment interface.

**Comment by pishguy** [comment]
@amreniouinnovent i'm sorry i don't know how can i implementing that

**Comment by amreniouinnovent** [comment]
@MahdiPishguy I am so busy currently try to use singleton class if it is urgent

**Comment by pishguy** [comment]
@amreniouinnovent i get `null` i'm not sure my code is correct:

https://github.com/MahdiPishguy/FlutterBlocFragmentTest

```dart
  int navigateToName(String fragmentName) {
    int fragmentIndex = -1;
    print('manager navigateToName:$fragmentIndex');

    _fragments.asMap().forEach((int index, Widget value) {
      if (value is Fragment && value.getRouteName() == fragmentName) {
        fragmentIndex = index;
      } else if (value is BlocProvider && value.child is Fragment && (value.child as Fragment).getRouteName() == fragmentName) {
        fragmentIndex = index;
        (value.child as Fragment).setData((value.child as Fragment).getParameter());
      } else if (value is MultiBlocProvider && value.child is Fragment && (value.child as Fragment).getRouteName() == fragmentName) {
        fragmentIndex = index;
        (value.child as Fragment).setData((value.child as Fragment).getParameter());
      }
    });
    print('manager navigateToName:$fragmentIndex');
    _backstack.add(fragmentIndex);
    _currentIndex = fragmentIndex;
    return fragmentIndex;
  }
```

Fragment1 

```dart 
class Fragment1 extends StatefulWidget implements Fragment {
  String myname;
  @override
  State<Fragment1> createState() => _Fragment1();

  ...

  @override
  String getParameter() {
    return 'aaaaaaaa';
  }

  @override
  void setData(String value) {
    myname = value;
  }
}
```
Fragment 

```dart
abstract class Fragment extends Widget{
  String getRouteName();
  String getTitle();
  String getParameter();

  void setData(String value) {}
}
```

**Comment by amreniouinnovent** [comment]
@MahdiPishguy could you pass a fixe value variable if it works then add parameter to  navigateToName(String fragmentName)

**Comment by pishguy** [comment]
@amreniouinnovent 

i get null again if i understand whats your mean

```dart
(value.child as Fragment).setData('11111');
```

**Comment by amreniouinnovent** [comment]
@MahdiPishguy if I got time I will add this implementation

**Comment by pishguy** [comment]
@amreniouinnovent can you got free time to help me today?

**Comment by amreniouinnovent** [comment]
@MahdiPishguy I have to deliver this week a new release so it too hard to support this week

**Comment by amreniouinnovent** [comment]
@MahdiPishguy you can use a singleton class for now

```
class GlobalData {
  factory GlobalData() => _instance ??= new GlobalData._();
  GlobalData._();
  //One instance, needs factory
  static GlobalData _instance;

  bool isDriverTablet = false;
}
```
Usage:
`GlobalData().isDriverTablet`

**Comment by pishguy** [comment]
@amreniouinnovent 
 
> 
> @MahdiPishguy you can use a singleton class for now
> 
> ```
> class GlobalData {
>   factory GlobalData() => _instance ??= new GlobalData._();
>   GlobalData._();
>   //One instance, needs factory
>   static GlobalData _instance;
> 
>   bool isDriverTablet = false;
> }
> ```
> 
> Usage:
> `GlobalData().isDriverTablet`

I get `stackoverflow` error

**Comment by amreniouinnovent** [comment]
@MahdiPishguy StackOverflow is related to your logic you call nested calls over and over

**Comment by pishguy** [comment]
@amreniouinnovent maybe, because i use that whenever i need to pass data :(

**Comment by pishguy** [comment]
@amreniouinnovent hi,

can you got free time to help me how can i implementing this feature?

thanks in advance

**Comment by amreniouinnovent** [comment]
@MahdiPishguy check the latest commit I added an example for passing the parameter
confirm if it works

**Comment by pishguy** [comment]
@amreniouinnovent thank you very much

**Comment by amreniouinnovent** [comment]
@MahdiPishguy You are welcome
